version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/parts_db
    depends_on:
      - db
    command: ["sh", "-c", "python -m app.migrations && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parts_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
